BloodDonorManagementSystem/Controllers/BloodsController.cs
using BloodDonorManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace BloodDonorManagementSystem.Controllers
{
    public class BloodsController : Controller
    {
        BloodDonorDbContext db = new BloodDonorDbContext();
        // GET: Bloods
        public ActionResult Index()
        {
            return View(db.Bloods.Include(b => b.Donors).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateBlood()
        {
            return PartialView("_CreateBlood");
        }
        [HttpPost]
        public PartialViewResult CreateBlood(Blood b)
        {
            Thread.Sleep(2500);
            if (ModelState.IsValid)
            {
                db.Bloods.Add(b);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditBlood(int id)
        {
            var b = db.Bloods.First(x => x.BloodId == id);
            return PartialView("_EditBlood", b);
        }
        [HttpPost]
        public PartialViewResult EditBlood(Blood b)
        {
            Thread.Sleep(2500);
            if (ModelState.IsValid)
            {
                db.Entry(b).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Bloods.First(x => x.BloodId == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int BloodId)
        {
            var b = new Blood { BloodId = BloodId };
            db.Entry(b).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BloodDonorManagementSystem/Views/Bloods/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-info">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12 px-5">
        <h3 class="col-7 mb-5" style="background-color: darkseagreen; text-align:center; padding-bottom:2px;">Entry Blood</h3>
        @Html.Action("CreateBlood")
    </div>
    <div class="col-1" style="background-color:lightgrey;">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
}

BloodDonorManagementSystem/Views/Bloods/Delete.cshtml
@model BloodDonorManagementSystem.Models.Blood
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3 class="col-3 mb-3" style="text-align:center;">Confirm delete</h3>
    </div>
    <div class="col-12">
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.BloodGroup, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.BloodGroup)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.BloodDetails, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.BloodDetails)

            </div>
        </div>       
        <div class="form-group row mb-1">

            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.BloodId)
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                </div>
            }
        </div>
    </div>
    <div class="col-1" style="background-color:lightgrey">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

BloodDonorManagementSystem/Views/Bloods/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-info">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <h3 class="col-7 mb-5" style="background-color: darkseagreen; text-align:center; padding-bottom:2px;">Edit Blood</h3>
        @Html.Action("EditBlood", new { id = ViewBag.Id })
    </div>
    <div class="col-1" style="background-color:lightgrey;">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
        $("#JourneyDate").val(formatDate($("#JourneyDate").val()));
        if ($("#EndDate").val() != "") {
            $("#EndDate").val(formatDate($("#EndDate").val()));
        }
        function formatDate(date) {
            var d = new Date(date),
                month = '' + (d.getMonth() + 1),
                day = '' + d.getDate(),
                year = d.getFullYear();

            if (month.length < 2)
                month = '0' + month;
            if (day.length < 2)
                day = '0' + day;

            return [year, month, day].join('-');
        }
    </script>
}

BloodDonorManagementSystem/Views/Bloods/Index.cshtml
@model IEnumerable<BloodDonorManagementSystem.Models.Blood>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3 class="mb-4" style="color:white; background-color:teal; text-align:center; padding:3px;">Blood Details</h3>
        <div class="d-flex justify-content-end mb-2">
            @Html.ActionLink("Add New Blood", "Create", "Bloods", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead style="background-color: darkseagreen">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.BloodGroup)</th>
                    <th>@Html.DisplayNameFor(x => x.BloodDetails)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr style="background-color:beige">
                        <td>@Html.DisplayFor(x => m.BloodGroup)</td>
                        <td>@Html.DisplayFor(x => m.BloodDetails)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Bloods", new { id = m.BloodId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Bloods", new {id=m.BloodId})" class="btn btn-danger btn-sm @(m.Donors.Count > 0 ? "disabled" :"")">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BloodDonorManagementSystem/Views/Bloods/_CreateBlood.cshtml
@model BloodDonorManagementSystem.Models.Blood
@using (Ajax.BeginForm("CreateBlood", "Bloods", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    LoadingElementId = "spinner",
    OnSuccess = "onSuccess"
}, new { id = "f" }))
{
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BloodGroup, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-5">
            @Html.EnumDropDownListFor(x => x.BloodGroup, new { @class = "form-select form-select-sm" })
            @Html.ValidationMessageFor(x => x.BloodGroup, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BloodDetails, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-5">
            @Html.TextBoxFor(x => x.BloodDetails, new { @class = "form-control form-control-sm", type = "money" })
            @Html.ValidationMessageFor(x => x.BloodDetails, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

BloodDonorManagementSystem/Views/Bloods/_EditBlood.cshtml
@model BloodDonorManagementSystem.Models.Blood
@using (Ajax.BeginForm("EditBlood", "Bloods", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    LoadingElementId = "spinner"

}, new { id = "f" }))
{
    @Html.HiddenFor(x => x.BloodId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BloodGroup, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-5">
            @Html.EnumDropDownListFor(x => x.BloodGroup, new { @class = "form-select form-select-sm" })
            @Html.ValidationMessageFor(x => x.BloodGroup, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BloodDetails, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-5">
            @Html.TextBoxFor(x => x.BloodDetails, new { @class = "form-control form-control-sm", type = "money" })
            @Html.ValidationMessageFor(x => x.BloodDetails, "", new { @class = "text-danger" })
        </div>
    </div>    
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
}