BloodDonorManagementSystem/Controllers/HospitalsController.cs
using BloodDonorManagementSystem.Models;
using BloodDonorManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace BloodDonorManagementSystem.Controllers
{
    public class HospitalsController : Controller
    {
        private readonly BloodDonorDbContext db = new BloodDonorDbContext();
        //GET: Hospitals
        public ActionResult Index()
        {
            var data = db.Hospitals
                .Include(x => x.HospitalPatients.Select(y => y.Patient))
                .ToList();
            return View(data);
        }
        public ActionResult Create()
        {
            ViewBag.Patients = db.Patients.ToList();
            var data = new HospitalInputModel();
            data.Patients.Add(new PatientViewModel());
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(HospitalInputModel model)
        {
            if (ModelState.IsValid)
            {
                var h = new Hospital
                {
                    HospitalName = model.HospitalName,
                    Address = model.Address,
                    Email = model.Email,
                    Location = model.Location
                };
                foreach (var x in model.Patients)
                {
                    h.HospitalPatients.Add(new HospitalPatient { PatientId = x.PatientId });
                }
                if (model.Picture.ContentLength > 0)
                {
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string fileName = Guid.NewGuid() + ext;
                    model.Picture.SaveAs(Path.Combine(Server.MapPath("~/Assets"), fileName));
                    h.Picture = fileName;
                }
                db.Hospitals.Add(h);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Patients = db.Patients.ToList();

            return View(model);
        }
        public JsonResult GetPaymentBill(int id)
        {
            var t = db.Patients.FirstOrDefault(x => x.PatientId == id);
            return Json(t == null ? 0 : t.PaymentBill);
        }
        public ActionResult CreateNewField(HospitalInputModel data)
        {
            ViewBag.Patients = db.Patients.ToList();
            data.Patients.Add(new PatientViewModel());
            return PartialView(data);
        }
        public ActionResult CreateV1()
        {

            return View();
        }
        public PartialViewResult CreateHospital()
        {
            ViewBag.Patients = db.Patients.ToList();

            return PartialView("_Hospital");
        }
    }
}

BloodDonorManagementSystem/Views/Hospitals/Create.cshtml
@model BloodDonorManagementSystem.ViewModel.HospitalInputModel
@{
    ViewBag.Title = "Create";
}

<div id="frm">
    <div class="row">
        <div class="col-12">
            <h3>Create new Hospital</h3>
            @using (Html.BeginForm("Create", "Hospitals", FormMethod.Post, new { id = "f", enctype = "multipart/form-data" }))
            {
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.HospitalName, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.HospitalName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.HospitalName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.Location, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Location, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="d-flex justify-content-between mb-1">
                    <h4>Tests</h4>
                    <button type="button" id="add" class="btn btn-secondary btn-sm">+</button>
                </div>
                for (var i = 0; i < Model.Patients.Count; i++)
                {

                    <div class="form-group row mb-1">
                        @Html.LabelFor(x => Model.Patients[i].PatientId, new { @class = "col-form-label col-2" })
                        <div class="col-4">
                            @Html.DropDownListFor(x => Model.Patients[i].PatientId, new SelectList(ViewBag.Patients, "PatientId", "PatientName"), "Select one", new { @class = "form-select select" })
                            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(x => Model.Patients[i].PaymentBill, new { @class = "col-form-label col-2" })
                        <div class="col-4">
                            @Html.TextBoxFor(x => Model.Patients[i].PaymentBill, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>
                }
                <div class="form-group mb-1">
                    <div class="col-4 offset-2">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section styles {
    <style>
        .col2 {
            display: grid;
            grid-template-columns: 2fr 1fr 2fr 1fr
        }
    </style>
}
@section scripts {
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script>
        $(() => {
            $('.select').change(function () {
                var p = $(this).attr("id").split("__")[0];
                console.log($(this).val());
                $.ajax({
                    type: "POST",
                    url: '/Hospitals/GetPaymentBill/' + $(this).val(),
                    dataType: "json",
                    success: data => {
                        console.log(data);
                        $(`#${p}__PaymentBill`).val(data);
                    }
                })
            });
            $("#add").click(() => {
                var data = $("#f").serialize();
                console.log(data);
                $.ajax({
                    type: "POST",
                    url: "/Hospitals/CreateNewField",

                    data: data,
                    success: r => {
                        $("#frm").html(r);
                    }
                });
            });
        });
    </script>
}

BloodDonorManagementSystem/Views/Hospitals/CreateNewField.cshtml
@model BloodDonorManagementSystem.ViewModel.HospitalInputModel
<div class="row">
    <div class="col-12">
        <h3>Create new Hospital</h3>
        @using (Html.BeginForm("Create", "Hospitals", FormMethod.Post, new { id = "f", enctype = "multipart/form-data" }))
        {
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.HospitalName, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.HospitalName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.HospitalName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Location, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="d-flex justify-content-between mb-1">
                <h4>Patients</h4>
                <button type="button" id="add" class="btn btn-secondary btn-sm">@*<i class="bi bi-plus"></i>*@+</button>
            </div>
            for (var i = 0; i < Model.Patients.Count; i++)
            {
                <div class="form-group row mb-1">
                    @Html.LabelFor(x => Model.Patients[i].PatientId, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.DropDownListFor(x => Model.Patients[i].PatientId, new SelectList(ViewBag.Patients, "PatientId", "PatientName"), "Select one", new { @class = "form-select select" })
                        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(x => Model.Patients[i].PaymentBill, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => Model.Patients[i].PaymentBill, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>
            }
            <div class="form-group mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>

BloodDonorManagementSystem/Views/Hospitals/CreateV1.cshtml
@model BloodDonorManagementSystem.ViewModel.HospitalInputModel
@{
    ViewBag.Title = "CreateV1";
}

<div class="row">
    <div class="col-12">
        <h3>Create new test entry</h3>
        @using (Html.BeginForm("Create", "Hospitals", FormMethod.Post, new { id = "f", enctype = "multipart/form-data" }))
        {
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.HospitalName, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.HospitalName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.HospitalName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Location, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Location, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="d-flex justify-content-between mb-1">
                <h4>Patients</h4>
                <button type="button" id="add" class="btn btn-secondary btn-sm">+</button>
            </div>
            <div id="child">
                @Html.Action("CreateHospital")
            </div>
            <div class="form-group mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>

                </div>
            </div>
        }
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        $(() => {
            $(document).on("change", ".select", function () {
                var p = $(this).attr("id");
                console.log(p);
                //console.log($(this).parent().parent().find("#PaymentBill"));
                var q = $(this).parent().parent().find("#PaymentBill");
                console.log(q);
                $.ajax({
                    type: "POST",
                    url: '/Hospitals/GetPaymentBill/' + $(this).val(),
                    dataType: "json",
                    success: data => {
                        console.log(data);
                        q.val(data);
                    }
                });
            })
            //$('.select').change(function () {
            //    var p = $(this).attr("id");
            //    console.log(p);
            //    //console.log($(this).parent().parent().find("#PaymentBill"));
            //    var q = $(this).parent().parent().find("#PaymentBill");
            //    console.log(q);

            //});
            $("#add").click(() => {

                $.ajax({
                    type: "GET",
                    url: "/Hospitals/CreateHospital",
                    success: r => {
                        console.log(r);
                        $("#child").append(r);
                    }
                });
            });
        });
    </script>
}

BloodDonorManagementSystem/Views/Hospitals/Index.cshtml
@model IEnumerable<BloodDonorManagementSystem.Models.Hospital>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3 style="color:white; background-color:teal; text-align:center; padding:3px;">Hospital Records</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Create New", "CreateV1", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead style="background-color:deepskyblue">
                <tr>
                    <th>@Html.DisplayNameFor(t => t.Picture)</th>
                    <th>@Html.DisplayNameFor(t => t.HospitalName)</th>
                    <th>@Html.DisplayNameFor(t => t.Address)</th>
                    <th>@Html.DisplayNameFor(t => t.Email)</th>
                    <th>@Html.DisplayNameFor(t => t.Location)</th>                   
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr style="background-color:lightgreen;">
                        <td style="width:70px" class="text-center">
                            <img src="~/Assets/@x.Picture" style="width:40px" class="rounded-circle" />
                        </td>
                        <td>@Html.DisplayFor(t => x.HospitalName)</td>
                        <td>@Html.DisplayFor(t => x.Address)</td>
                        <td>@Html.DisplayFor(t => x.Email)</td>
                        <td>@Html.DisplayFor(t => x.Location)</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="border-end-0">&nbsp;</td>
                        <td colspan="6" class="border-start-0">
                            <h4 style="background-color:navajowhite; text-align:center; padding:3px;">Patient</h4>
                            <table class="table table-bordered">
                                <thead style="background-color:lemonchiffon">
                                    <tr>
                                        <th>Patient Name</th>
                                        <th>Payment Bill</th>
                                    </tr>
                               </thead>
                                @foreach (var y in x.HospitalPatients)
                                {
                            <tr style="background-color: beige">
                                
                                <td>@y.Patient.PatientName</td>
                                <td class="text-end">@y.Patient.PaymentBill.ToString("0.00")</td>
                            </tr>
                                }
                                <tr>
                                    <td colspan="2" class="text-end pe-2">
                                        Total: @x.HospitalPatients.Sum(t => t.Patient.PaymentBill)
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BloodDonorManagementSystem/Views/Hospitals/_Hospital.cshtml
@model BloodDonorManagementSystem.ViewModel.PatientViewModel
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.PatientId, new { @class = "col-form-label col-2" })
    <div class="col-4">
        @Html.DropDownListFor(x => x.PatientId, new SelectList(ViewBag.Patients, "PatientId", "PatientName"), "Select one", new { @class = "form-select select" })
        @Html.ValidationMessageFor(x => x.PatientId, "", new { @class = "text-danger" })
    </div>
    @Html.LabelFor(x => x.PaymentBill, new { @class = "col-form-label col-2" })
    <div class="col-4">
        @Html.TextBoxFor(x => x.PaymentBill, new { @class = "form-control", @readonly = "true" })
    </div>
</div>