BloodDonorManagementSystem/Controllers/DonorsController.cs
using BloodDonorManagementSystem.Models;
using BloodDonorManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloodDonorManagementSystem.Controllers
{
    public class DonorsController : Controller
    {
        BloodDonorDbContext db = new BloodDonorDbContext();
        // GET: Donors
        public ActionResult Index()
        {
            return View(db.Donors.Include(x => x.Blood).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.Bloods = db.Bloods.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(DonorInputModel c)
        {
            if (ModelState.IsValid)
            {
                var Donor = new Donor
                {
                    DonorName = c.DonorName,
                    Address = c.Address,
                    Email = c.Email,
                    Phone = c.Phone,
                    DonationDate = c.DonationDate,
                    IsAvailable = c.IsAvailable,
                    BloodId = c.BloodId
                };
                string ext = Path.GetExtension(c.Picture.FileName);
                string f = Guid.NewGuid() + ext;
                c.Picture.SaveAs(Server.MapPath("~/Assets/") + f);
                Donor.Picture = f;
                db.Donors.Add(Donor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Bloods = db.Bloods.ToList();
            return View(c);
        }
        public ActionResult Edit(int id)
        {
            var t = db.Donors.First(x => x.DonorId == id);
            ViewBag.Bloods = db.Bloods.ToList();
            ViewBag.CurrentPic = t.Picture;
            return View(new DonorEditModel { DonorId = t.DonorId, DonorName = t.DonorName, Address = t.Address, Email = t.Email, Phone = t.Phone, DonationDate=t.DonationDate, BloodId = t.BloodId/*, Picture = t.Picture*/ });
        }
        [HttpPost]
        public ActionResult Edit(DonorEditModel t)
        {
            var Donor = db.Donors.First(x => x.DonorId == t.DonorId);
            if (ModelState.IsValid)
            {

                Donor.DonorName = t.DonorName;
                Donor.Address = t.Address;
                Donor.Email = t.Email;
                Donor.Phone = t.Phone;
                Donor.DonationDate = t.DonationDate;
                Donor.IsAvailable = t.IsAvailable;
                if (t.Picture != null)
                {
                    string ext = Path.GetExtension(t.Picture.FileName);
                    string f = Guid.NewGuid() + ext;
                    t.Picture.SaveAs(Server.MapPath("~/Assets/") + f);
                    Donor.Picture = f;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CurrentPic = Donor.Picture;
            ViewBag.Bloods = db.Bloods.ToList();
            return View(t);
        }
        public ActionResult Delete(int id)
        {
            return View(db.Donors.Include(x => x.Blood).First(x => x.DonorId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            Donor t = new Donor { DonorId = id };
            db.Entry(t).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BloodDonorManagementSystem/Views/Donors/Create.cshtml
@model BloodDonorManagementSystem.ViewModel.DonorInputModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <h2 class="col-7 mb-5" style="background-color: darkseagreen; text-align:center; padding-bottom:2px;">Entry Donor</h2>
        @using (Html.BeginForm("Create", "Donors", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.DonorName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.DonorName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.DonorName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BloodId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.DropDownListFor(x => x.BloodId, new SelectList(ViewBag.Bloods, "BloodId", "BloodGroup"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.BloodId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.DonationDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.DonationDate, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.DonationDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.IsAvailable, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.CheckBoxFor(x => x.IsAvailable, new { @class = "form-check" })
                    @Html.ValidationMessageFor(x => x.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-1" style="background-color:lightgrey">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
}

BloodDonorManagementSystem/Views/Donors/Delete.cshtml
@model BloodDonorManagementSystem.Models.Donor
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3 class="col-4 mb-3" style="text-align:center;">Are you sure want to delete?</h3>

        @Html.HiddenFor(x => x.DonorId)
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.DonorName, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.DonorName)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Blood.BloodGroup, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.Blood.BloodGroup)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.Address)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.Email)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.Phone)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.DonationDate, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.DonationDate)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.IsAvailable, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                @Html.DisplayFor(x => x.IsAvailable)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-5">
                <img src="~/Assets/@Model.Picture" class="img-thumbnail" style="width:120px; height:110px;" />
            </div>
        </div>
        @using (Html.BeginForm("Delete", "Donors", new { id = Model.DonorId }, FormMethod.Post))
        {

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
        }
    </div>
    <div class="col-1" style="background-color:lightgrey">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

BloodDonorManagementSystem/Views/Donors/Edit.cshtml
@model BloodDonorManagementSystem.ViewModel.DonorEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <h3 class="col-7 mb-5" style="background-color: darkseagreen; text-align:center; padding-bottom:2px;">Edit Donor</h3>
        @using (Html.BeginForm("Edit", "Donors", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.DonorId)
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.DonorName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.DonorName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.DonorName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BloodId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.DropDownListFor(x => x.BloodId, new SelectList(ViewBag.Bloods, "BloodId", "BloodGroup"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.BloodId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Email, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.DonationDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.DonationDate, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.DonationDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.IsAvailable, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.CheckBoxFor(x => x.IsAvailable, new { @class = "form-check" })
                    @Html.ValidationMessageFor(x => x.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-5">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
                <div class="col-1">
                    <img src="~/Assets/@ViewBag.CurrentPic" class="img-thumbnail" style="width:80px; height:75px;" />
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>
        }
    </div>
    <div class="col-1" style="background-color:lightgrey">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
}

BloodDonorManagementSystem/Views/Donors/Index.cshtml
@model IEnumerable<BloodDonorManagementSystem.Models.Donor>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3 class="mb-4" style="color:white; background-color:teal; text-align:center; padding:3px;">Donor Details</h3>
        <div class="d-flex justify-content-end mb-2">
            @Html.ActionLink("Add New Donor", "Create", "Donors", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead @*class="bg-secondary text-white"*@ style="background-color: darkseagreen">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.DonorName)</th>
                    <th>@Html.DisplayNameFor(x => x.Blood.BloodGroup)</th>
                    <th>@Html.DisplayNameFor(x => x.Address)</th>
                    <th>@Html.DisplayNameFor(x => x.Email)</th>
                    <th>@Html.DisplayNameFor(x => x.Phone)</th>
                    <th>@Html.DisplayNameFor(x => x.DonationDate)</th>
                    <th>@Html.DisplayNameFor(x => x.IsAvailable)</th>
                    <th>@Html.DisplayNameFor(x => x.Picture)</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                <tr style="background-color:beige">
                    <td>@Html.DisplayFor(x => m.DonorName)</td>
                    <td>@Html.DisplayFor(x => m.Blood.BloodGroup)</td>
                    <td>@Html.DisplayFor(x => m.Address)</td>
                    <td>@Html.DisplayFor(x => m.Email)</td>
                    <td>@Html.DisplayFor(x => m.Phone)</td>
                    <td>@Html.DisplayFor(x => m.DonationDate)</td>
                    <td>@(m.IsAvailable ? "Yes": "No")</td>
                    <td><img src="~/Assets/@m.Picture" class="rounded-circle" style="width:42px; height:42px;" /></td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", "Donors", new { id = m.DonorId }, new { @class = "btn btn-secondary btn-sm" })
                        <a href="@Url.Action("Delete", "Donors", new {id=m.DonorId})" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>